# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scheduler.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'scheduler.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fscheduler.proto\x12\tscheduler\"J\n\nJobRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0c\n\x04task\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\x12\x10\n\x08priority\x18\x04 \x01(\x05\"\x1e\n\x0bJobResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\"\n\x10JobStatusRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"#\n\x11JobStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x95\x01\n\x0cJobScheduler\x12:\n\tSubmitJob\x12\x15.scheduler.JobRequest\x1a\x16.scheduler.JobResponse\x12I\n\x0cGetJobStatus\x12\x1b.scheduler.JobStatusRequest\x1a\x1c.scheduler.JobStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scheduler_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOBREQUEST']._serialized_start=30
  _globals['_JOBREQUEST']._serialized_end=104
  _globals['_JOBRESPONSE']._serialized_start=106
  _globals['_JOBRESPONSE']._serialized_end=136
  _globals['_JOBSTATUSREQUEST']._serialized_start=138
  _globals['_JOBSTATUSREQUEST']._serialized_end=172
  _globals['_JOBSTATUSRESPONSE']._serialized_start=174
  _globals['_JOBSTATUSRESPONSE']._serialized_end=209
  _globals['_JOBSCHEDULER']._serialized_start=212
  _globals['_JOBSCHEDULER']._serialized_end=361
# @@protoc_insertion_point(module_scope)
